version: '3'
services:
  database:
    image: 'mongo'
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: $INITDB_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $INITDB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $INITDB_PASSWORD
    volumes:
      - ./home/mongodb:/home/mongodb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - '27017-27019:27017-27019'