name: freeCodingCamp Algorithms CI
on:
  push:
    paths:
      - 'algorithms-js/**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      working-directory: ./algorithms-js
      run: |
        npm ci
    - name: npm test
      working-directory: ./algorithms-js
      run: |
        npm run test-ci
