name: Demographic Data Analyzer ci
on:
  push:
    paths:
      - "python/demographic-data-analyzer/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./python/demographic-data-analyzer
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run python unit tests
        working-directory: ./python/demographic-data-analyzer
        run: |
          python -m unittest test_module
